---
title: "Topic Models"
author: "Sarthak Saluja"
date: "2022-08-04"
output: html_document
---

Purpose : 

1. Create a separate dfm of tweets 
2. Find optimal topic no.
3. 

Create workspace : 

```{r, message=F}
rm(list= ls())
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(quanteda)
library(stm)
library(topicmodels)
library(dplyr)
library(wordcloud)
library(topicmodels)
library(stm)
library(ggplot2)
library(tidyr)
library(tidytext)
library(ggthemes)
library(furrr)
library(purrr)
#plan(multicore)
```

Load in the data 

```{r}
network_tweets <- readRDS('tweets/network_tweets.rds')
coredfm <- readRDS('dfm/coredfm.rds')
peripherydfm <- readRDS('dfm/peripherydfm.rds')
```

Preprocessing :

```{r}
unique_tweets <- network_tweets |> 
  filter(referenced_tweets_type != 'retweeted')

unique_tweets$created_at <- as.Date(unique_tweets$created_at)

range(unique_tweets$created_at)
```

Make dfm : 

```{r}
# remove common occurring hashtags 

hashtags <- stringr::str_extract_all(unique_tweets$text.x, "#\\w+")
hashtags <- unlist(hashtags)
hashtags_to_remove <- unique(hashtags)

hashtags_to_remove

# popular hashtags 

top_20_hashtags <- hashtags |> 
  group_by(tag) |> 
  summarize(n = n()) |> 
  arrange(-n) |> 
  head(20) |> 
  select(tag) |>
  unlist()
  

```

```{r}
keywords <- c('farmers', 'protest')

make_dfm <- function(tweets = support_tweets, 
                     core = 1){
  
  dfm <- tweets |> 
    filter(!is.na(cores) & 
             referenced_tweets_type != 'retweeted' & 
             is_core == core) |> 
    corpus(text = 'text.x') |> 
    tokens(remove_punct = TRUE, 
           remove_symbols = TRUE, 
           remove_numbers = TRUE, 
           remove_url = TRUE) |> 
    tokens_remove(c(stopwords('en'), 
                    hashtags_to_remove, 
                    keywords)) |> 
    dfm() |>
    dfm_group(groups = created_at) |>
    dfm_trim(min_termfreq = 20)
  
  return(dfm)
}

coredfm <- make_dfm(unique_tweets, core = 1)
peripherydfm <- make_dfm(unique_tweets, core = 0)

saveRDS(coredfm, 'dfm/coredfm.rds')
saveRDS(peripherydfm, 'dfm/peripherydfm.rds')

coredfm
peripherydfm
```


```{r}
core_input <- convert(coredfm, to = 'tm')
periphery_input <- convert(peripherydfm, to = 'tm')

K_core_results <- FindTopicsNumber(
  core_input,
  topics = seq(from = 5, to = 50, by = 10),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 124),
  verbose = TRUE, 
  mc.cores = 3L
)

K_periphery_results <- FindTopicsNumber(
  core_input,
  topics = seq(from = 5, to = 50, by = 10),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 123),
  verbose = TRUE, 
  mc.cores = 3L
)

FindTopicsNumber_plot(K_core_results)
FindTopicsNumber_plot(K_periphery_results)


saveRDS(K_core_results, 'topic models/K_core_results.rds')
saveRDS(K_periphery_results, 'topic models/K_periphery_results.rds')
```


```{r}
ctm <- LDA(coredfm, 
           25, 
           method="Gibbs", 
           control=list(iter = 50, seed = 1))

ptm <- LDA(peripherydfm, 
           25, 
           method="Gibbs", 
           control=list(iter = 50, seed = 11))

```


Analyze top terms for each topic : 

```{r}
core_terms <- data.frame(t(data.frame(terms(ctm, 20))))
periphery_terms <- data.frame(t(data.frame(terms(ptm, 20))))


core_labels <- data.frame(topics = 1:25, 
           terms = do.call(paste, c(core_terms, sep=", ")))


periphery_labels <- data.frame(topics = 1:25, 
           terms = do.call(paste, c(periphery_terms, sep=", ")))

write.csv(core_labels, 'topic models/core_labels.csv', 
          row.names = F)

write.csv(periphery_labels, 'topic models/periphery_labels.csv', 
          row.names = F)
```

Gamma values : 

```{r}
gamma_core <- tidy(ctm, 
                   matrix = 'gamma')

gamma_periphery <- tidy(ptm, 
                   matrix = 'gamma')


saveRDS(gamma_core, 'topic models/gamma_core.rds')
saveRDS(gamma_core, 'topic models/gamma_periphery.rds')

```

Matching Topics : 

```{r}
select_topic <- function(topic_core, 
                          topic_periphery, 
                          topic_name, 
                          save = NULL){
  core <- gamma_core |>
    filter(topic == topic_core) |> 
    mutate(name = topic_name) |> 
    select(document, name, gamma)
  
  periphery <- gamma_periphery |>
    filter(topic == topic_periphery) |> 
    mutate(name = topic_name) |> 
    select(document, name, gamma)
  
  topic <- core |> 
    full_join(periphery, by = 'document') |> 
    select(document, gamma_core = gamma.x, gamma_periphery = gamma.y)
  
  
  if(save == T){
    write.csv(topic, paste0('topics/', topic_name, '.csv'))
    return(topic)
  }else(
    return(topic)
  )
}


police <- select_topic(topic_core = 2, 
                       topic_periphery = 24, 
                       topic_name = 'police', 
                       save = T)

transnational <- select_topic(topic_core = 5, 
                       topic_periphery = 11, 
                       topic_name = 'transnational', 
                       save = T)

media <- select_topic(topic_core = 6, 
                       topic_periphery = 20, 
                       topic_name = 'media', 
                       save = T)

opposition <- select_topic(topic_core = 11, 
                       topic_periphery = 13, 
                       topic_name = 'opposition', 
                       save = T)

jazzy <- select_topic(topic_core = 12, 
                       topic_periphery = 5, 
                       topic_name = 'jazzy', 
                       save = T)

rihanna <- select_topic(topic_core = 18, 
                       topic_periphery = 6, 
                       topic_name = 'rihanna', 
                       save = T)

msp <- select_topic(topic_core = 17, 
                       topic_periphery = 14, 
                       topic_name = 'msp', 
                       save = T)

borders <- select_topic(topic_core = 22, 
                       topic_periphery = 23, 
                       topic_name = 'border', 
                       save = T)



```











Find optimal value for K : 

```{r}

find_K <- function(twdfm){
  
  stm_input <- convert(twdfm, to = "stm") # Create an stm object

  # Check values for topics = 5, 10, 15, 20, 25

  models <- data_frame(K = c(5, 10, 15, 20, 25)) %>%
          mutate(topic_model = future_map(K, ~stm(stm_input$documents, K = .,
                                                  verbose = FALSE, 
                                                  vocab = stm_input$vocab, 
                                                  data = stm_input$meta, 
                                                  seed = TRUE, 
                                                  init.type = "Spectral"))) # Parallel topic extraction

  heldout <- make.heldout(stm_input$documents, stm_input$vocab)
  
  k_result <- models %>% 
    mutate(exclusivity = map(topic_model, exclusivity), 
           coherence = map(topic_model, semanticCoherence, stm_input$documents), 
           heldout = map(topic_model, eval.heldout, heldout$missing))
  
  return(k_result)
    
}


K_core <- find_K(coredfm)
K_periphery <- find_K(peripherydfm)

```

Plot fit : 

```{r}
plot_K_all_metrics <- function(group){
  
  if(group == 'core'){
    result <- K_core
  } else if (group == 'periphery'){
    result <- K_periphery
  }
  
  all_metrics <- result %>% 
    transmute(K, 
              'Coherence' = map_dbl(coherence, mean), 
              'Held Out Likelihood' = map_dbl(heldout, 'expected.heldout'), 
              'Exclusivity' = map_dbl(exclusivity, mean)) %>% 
    pivot_longer(cols = c('Coherence', "Held Out Likelihood", 'Exclusivity'), 
                 names_to = 'Metric', values_to = 'Values') %>% 
    ggplot(aes(x = K, y = Values, color = Metric)) + 
    geom_line() + 
    facet_wrap(~Metric, scales = 'free_y') + 
    theme_bw() + 
    ggtitle(paste0('Main Metrics vs K for group : ', group)) 
  
  return(all_metrics)
}

plot_K_tradeoff <- function(group){
  
  if(group == 'core'){
    result <- K_core
  } else if (group == 'periphery'){
    result <- K_periphery
  }
  
  tradeoff <- result %>%
    select(K, exclusivity, coherence) %>%
    filter(K %in% c(5, 10, 15, 20, 25)) %>% 
    unnest() %>% 
    mutate(K = as.factor(K)) %>% 
    ggplot(aes(x = coherence, y = exclusivity, color = K)) + 
    geom_point() + 
    geom_smooth(method = 'lm', se = FALSE) +
    facet_wrap(~K) +
    theme_bw() + 
    ggtitle(paste0('Exclusivity vs Coherence for group : '), group)
  
  return(tradeoff)
}

plot_K_all_metrics('core')
plot

```

```{r}
library('ldatuning')
?FindTopicsNumber



```





